### PR TITLE
Add the support to iDynTree

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
Hi @stephane-caron! Thanks for implementing this library. This PR adds support to [iDynTree](https://github.com/robotology/idyntree).

The PR fixes also a typo in the readme

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
I've just noticed that the test is missing. I need to implement it

**Comment by stephane-caron** [comment]
Oh, I hadn't noticed that [idyntree](https://pypi.org/project/idyntree/) is on PyPI. Then we can directly adapt the existing tests for now :wink: 

> I've just noticed that the test is missing. I need to implement it

:+1:

**Review by stephane-caron — COMMENTED** [review]
LGTM :+1: Unit tests aside, all other suggestions are nits.

**Comment by stephane-caron** [comment]
Awesome, let's merge and spin a release for this new loader :+1:

**Pull request merged**
